accounts/urls.py
from django.urls import path, reverse_lazy
from .views import SignupView, LoginView, LogoutView, IndexView
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
 # パスワードリセットフォーム表示
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset_form.html',
        subject_template_name='accounts/mail_template/reset/subject.txt',
        email_template_name='accounts/mail_template/reset/message.txt',
        html_email_template_name='accounts/mail_template/reset/message.html',
        success_url='done/'  # 確実に正しいパスを指定
    ), name='password_reset'),

 # メール送信完了ページ
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    
# 確認URL（Djangoが生成するリンク用）
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'
    ), name='password_reset_confirm'),

 # 完了通知ページ
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),]

blog_app/urls.py
from django.urls import path
from . import views

app_name='blog_app'

urlpatterns=[
    path('', views.IndexView, name='index'),
    
]

blogkadai/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('blog_app.urls')),
    
    path('accounts/', include('accounts.urls')),
    
    path('', include('formapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

formapp/urls.py
from django.urls import path
from .views import ListClass, FormClass
from . import views

app_name = 'formapp'

urlpatterns = [
    path('list/', ListClass.as_view(), name='list'),  # リスト表示
    path('create/', FormClass.as_view(), name='create'),  # フォーム表示
    path('delete/<int:post_id>',views.delete_form,name='delete')
]

blog_app/models.py
from django.db import models

class BlogPost(models.Model):
    CATEGORY=(
        ('keyboard','キーボード'),
        ('mouse','マウス'),
        ('mousepad','マウスパッド'),
        ('pc','PC'),
    )
    
    title=models.CharField(
        verbose_name='タイトル',
        max_length=200
    )
    content=models.TextField(
        verbose_name='本文'
    )
    
    posted_at=models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )
    
    category=models.CharField(
        verbose_name='カテゴリ',
        max_length=50,
        choices=CATEGORY
    )
    
    def __str__(self):
        return self.title

blog_app/views.py
from django.shortcuts import render
from .models import BlogPost


def IndexView(request):
    # 投稿日時で降順に並び替えたすべてのレコードを取得
    records = BlogPost.objects.order_by('-posted_at')
    
    # カテゴリ別にフィルタリングしたレコードを取得
    keyboard_records = BlogPost.objects.filter(category="keyboard").order_by('-posted_at')
    mouse_records = BlogPost.objects.filter(category="mouse").order_by('-posted_at')
    mousepad_records = BlogPost.objects.filter(category="mousepad").order_by('-posted_at')
    pc_records = BlogPost.objects.filter(category="pc").order_by('-posted_at')
    
    # HTMLテンプレートに渡すコンテキスト辞書を作成
    context = {
        'records': records,
        'keyboard_records': keyboard_records,
        'mouse_records': mouse_records,
        'mousepad_records': mousepad_records,
        'pc_records':pc_records,
    }

    # テンプレートをレンダリング
    return render(request, 'index.html', context)

blog_app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Recommended devices</title>
        <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
        <script src={% static 'js/scripts.js'%}></script>
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top"id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">BlogHOME</a> 
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse"id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                Logout
                            </a>
                            <form id="logout-form" method="POST" action="{% url 'accounts:logout' %}" style="display: none;">
                                {% csrf_token %}
                            </form>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'formapp:create'%}">投稿</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'formapp:list'%}">おすすめ一覧</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login'%}">Login</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link" href="#about">サイトについて</a></li>
                        <li class="nav-item"><a class="nav-link" href="#projects">デバイス</a></li>
                        <li class="nav-item"><a class="nav-link" href="#pc">PC</a></li>
                        <li class="nav-item"><a class="nav-link" href="#signup">お問い合わせ</a></li>

                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
         <style>
            header{background-color: white;}
         </style>    
        <header class="masthead" style="background: url({% static 'assets/img/black_00104.jpg' %})">
            <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
                <div class="d-flex justify-content-center">
                    <div class="text-center">
                        <h1 class="mx-auto my-0 text-uppercase" >MyDevices</h1>
                        <h2 class="text-white-50 mx-auto mt-2 mb-5"></h2>
                        <a class="btn btn-primary" href="#about">Get Started</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="about-section text-center" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8">
                        <h2 class="text-white mb-4">Device introduction</h2>
                        <p class="text-white-50">
                            普段="text-white-50">
                            普段使っているデバイスを紹介します、参考になれば幸いです。
                            
                        </p>
                    </div>
                </div>
                <img class="img-fluid" src={% static "assets/img/UNI_DSC9455_TP_V.jpg" %} alt="..." />
            </div>
        </section>
        <!-- Projects-->
        <section class="projects-section bg-light" id="projects">
            <div class="container px-4 px-lg-5">
                <!-- Featured Project Row-->
                <div class="row gx-0 mb-4 mb-lg-5 align-items-center">
                    <div class="col-xl-8 col-lg-7"><img class="img-fluid mb-3 mb-lg-0" src={% static "assets/img/如月れんー真上RGBあり背景あり.jpg" %} alt="..." /></div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="featured-text text-center text-lg-left">
                            {% for record in keyboard_records %}
                            <h4>{{record.title}}</h4>
                            <p class="text-black-50 mb-0">{{record.content}}</p>
                            {% endfor %}
                        </div>
                        <hr class='my-4' />
                    </div>
                </div>
                <!-- Project One Row-->
                <div class="row gx-0 mb-5 mb-lg-0 justify-content-center">
                    <div class="col-lg-6"><img class="img-fluid" src={% static "assets/img/logitech-pro-x-superlight-wireless-mouse-00.jpg" %} alt="..." /></div>
                    <div class="col-lg-6">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-left">
                                    {% for record in mouse_records %}
                                    <h4 class="text-white">{{record.title}}</h4>
                                    <p class="mb-0 text-white-50">{{record.content}}</p>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project Two Row-->
                <div class="row gx-0 justify-content-center">
                    <div class="col-lg-6"><img class="img-fluid" src={% static "assets/img/P1170440.jpg" %} alt="..." /></div>
                    <div class="col-lg-6 order-lg-first">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-right">
                                    {% for record in mousepad_records %}
                                    <h4 class="text-white">{{record.title}}</h4>
                                    <p class="mb-0 text-white-50">{{record.content}}</p>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- pc-->
        <section class="bg-light" id="pc">
            <div class="container px-4 px-lg-5">
                <!-- Featured Project Row-->
                <div class="row gx-0 mb-4 mb-lg-5 align-items-center">
                    <div class="col-xl-8 col-lg-7"><img class="img-fluid mb-3 mb-lg-0" src={% static "assets/img/dospara-y_12794_8_d_20230706160315.jpg" %} alt="..." /></div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="featured-text text-center text-lg-left">
                            {% for record in pc_records %}
                            <h4>{{record.title}}</h4>
                            <p class="text-black-50 mb-0">{{record.content}}</p>
                            {% endfor %}
                        </div>
                        <hr class='my-4' />
                    </div>
                </div>

        <!-- Signup-->
        <section class="signup-section" id="signup" style="background: url({% static 'assets/img/black_00039.jpg' %})">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-md-20 col-lg-20  text-center">
                        <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
            <form action="https://script.google.com/macros/s/AKfycbyO1q-RGDOdTkOTvxoXq-TOBmCaJg5QkL5o2NLs3AI/dev" method="POST">
                <h2 class="text-white mb-5">お問い合わせ
                </h2>  
                <i class="far fa-paper-plane"></i>
                <label for="name">Name:</label>
                <input type="text" name="name" id="name" placeholder="Your name" maxlength="30" required></input>
                
                <label for="email">Email:</label>
                <input type="email" name="email" id="email" placeholder="Your email" maxlength="30" required></input>
                
                <label for="message">Message:</label>
                <textarea name="message" id="message" placeholder="Your message" required></textarea>
                
                <button type="submit">Send</button>
                
                <div class="status-message">
                    <!-- ステータスメッセージは送信成功時やエラー時に表示される予定です -->
                        </div>
                    </div>
                </div>
            </form>
        </section>
        <!-- Contact-->
        <section class="contact-section bg-black">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Address</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50">大分情報ITクリエイター専門学校</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-envelope text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Email</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50"><a href="#!">ooi2472030@stu.o-hara.ac.jp</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-mobile-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Phone</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50">080-4693-3711</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="social d-flex justify-content-center">
                    <a class="mx-2" href="https://x.com/Razu_123"><i class="fab fa-twitter"></i></a>
                    <a class="mx-2" href="https://www.facebook.com/?locale=ja_JP"><i class="fab fa-facebook-f"></i></a>
                    <a class="mx-2" href="https://github.co.jp/"><i class="fab fa-github"></i></a>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; Your Website 2023</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>